### ISSUE TITLE
库大小超限了

### ISSUE THREAD

**Issue by EmptyDreams** [2X-ercha/Twikoo-Magic#4]
库大小超过50MB，JSD不给用了

**Comment by noionion** [comment]
抱歉，最近才看到，我已经好久没维护了。不过master分支是没有50m限制的来着

**Comment by EmptyDreams** [comment]
> 抱歉，最近才看到，我已经好久没维护了。不过master分支是没有50m限制的来着

emm是吗，不过当时我确实是收到反馈说评论区表情包挂了，然后确认了一下才过来发issue的

**Comment by noionion** [comment]
可能是早期的时候链接没有锁上@master
