### ISSUE TITLE
建议修改jsd源为 ”github-do.panbaidu.cn“

### ISSUE THREAD

**Issue by 1834423612** [2X-ercha/Twikoo-Magic#6]
https://github-do.panbaidu.cn/
使用这个速度比jsd快了好几倍，超赞！推荐

[**修改后的**](https://github-do.panbaidu.cn//https://raw.githubusercontent.com/2x-ercha/twikoo-magic/master/image/QQ/0.gif)比[**原来的**](https://cdn.jsdelivr.net/gh/2x-ercha/twikoo-magic@master/image/QQ/0.gif)显示速度要更快

**Comment by noionion** [comment]
抱歉，邮件通知大概被我略过去了，现在才看到。

不过这个源貌似是再套了一层raw.githubusercontent.com，然后国内源我又本身不太敢用，经常国内人白嫖着白嫖着就裂开了。可以作为一种方式

**Comment by noionion** [comment]
测试了一下，很多链接不可用
